language: node_js

node_js:
  - "node"

install:
  - npm install

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: dist
  target_branch: gh-pages
  