language: node_js

node_js:
  - "node"

install:
  - npm install

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: build
  target_branch: gh-pages

notifications:
  email:
    on_success: never
    on_failure: always
